- name: Deploy to ec2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 instance
      ec2:
        instance_type: t2.micro
        image: ami-085925f297f89fce1
        region: us-east-1
        key_name: presentation
        vpc_subnet_id_: subnet-5c43bc7d
        assign_public_ip: yes
        wait: yes
        count: 1
        group: eshop
        aws_access_key: "ASIA5NVQRWVCMDFMEYCZ"
        aws_secret_key: "aws_secret_access_key=Zg4U8dxqV/Zl5zcKD+eP/Bio2twQI175Tc9BcKde"
        security_token: "FwoGZXIvYXdzEBEaDEz/UdOMqckN+vwuhSLBAdvoYuaY2jQLaZu6NXQypGB1rxn+oE5d0+rop8funmGWpgK9AG6FuHyMnGI/45hSaSunX8e3TQ1tsheBL1DQ96WV6GB+xiSNwlWkLf06fCg9cD5nh2Z+YZllzt2PZA9eJMH4XsIJeC7Sd5wIE80WIPCNL+2vesny4x9EdhiwdxSr0onZ4Pyw+FS1dYGMTZkt5GjEwjDvGdyqh7zxJvrfpkB8pNATRFLRtswjmeZUrJ9AvpXygB7A9Rek1U8OE3+YINIor/fq9QUyLa9xr9ke/sG3NYxmm+wDk45qzs5MWWVw3dnL3NaQ35PeadNnHeV7FDvtmqzgvg=="
    - name: Add instance to group
      add_host: hostname={{ item.public_dns_name }} groupname=launched
      with_items: '{{ec2.instances}}'

    - name: Wait for SSH connection
      wait_for: host={{ item.public_dns_name }} port=22 delay=30 timeout=300 state=started
      with_items: '{{ec2.instances}}'

- name: Configure EC2
  hosts: launched
  connection: ssh

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      become: yes

    - service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Get project files from Git
      git:
        repo: 'https://github.com/Collda/Kulm00_4IT572_FINAL.git'
        dest: ./app

    - name: Build Dockerized e-shop
      shell: cd ./app && docker build -t eshop:latest .
      become: yes

    - name: Run Dockerized e-shop
      shell: docker run -p 80:3000 eshop:latest
      async: 90
      poll: 0
      become: yes

    - wait_for: port=80
