- name: Deploy to ec2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 instance
      ec2:
        instance_type: t2.micro
        image: ami-085925f297f89fce1
        region: us-east-1
        key_name: presentation
        vpc_subnet_id_: subnet-5c43bc7d
        assign_public_ip: yes
        wait: yes
        count: 1
        group: eshop
        aws_access_key: "ASIA5NVQRWVCDU4D6P62"
        aws_secret_key: "/KEzs9uJchYFayHSNvKs0uoCeS+yy2HyzHUXXq8n"
        security_token: "FwoGZXIvYXdzEBMaDNnePyVYUkNN0msb8SLBAbIeu2KxtRTlDhTzc4mtJ5/d7kZjIYQyFabf28U+1DilI0H7m3y9BHppqtcvU0iaCFvt2R16ze61is6SwRjNI5jMYcDoj+no2B0APkE0ORDCvnGfx1cBq6N6b6ttioOOhF3vD8OZRUnYQkIHsXyDRuYO3G9jWwv6UlK7dAWxd9OjF8+qZguE+ox/MYqIMRZ4jLtmG/w0ubZotKM2WV2mNKOGDkVKphdsv6Z51MjHWiHpS9kFD0shNz09Z4b+JvmMQjoo8LPr9QUyLXF8wXNq+DmIMu3wxRQBbvzUdM+/hkzUilEHoBeXqJEXV7If0gK1G5+gvu8a3Q=="
    - name: Add instance to group
      add_host: hostname={{ item.public_dns_name }} groupname=launched
      with_items: '{{ec2.instances}}'

    - name: Wait for SSH connection
      wait_for: host={{ item.public_dns_name }} port=22 delay=30 timeout=300 state=started
      with_items: '{{ec2.instances}}'

- name: Configure EC2
  hosts: launched
  connection: ssh

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      become: yes
    - service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Get project files from Git
      git:
        repo: 'https://github.com/Collda/Kulm00_4IT572_FINAL.git'
        dest: ./app
    - name: Build Dockerized e-shop
      shell: cd ./app && docker build -t eshop:latest .
      become: yes
    - name: Run Dockerized e-shop
      shell: docker run -p 80:3000 eshop:latest
      async: 90
      poll: 0
      become: yes
    - wait_for:
        port: 80
